builds:
  - id: crossplane-lint
    main: ./cmd/crossplane-lint
    env:
      - CGO_ENABLED=0
    binary: crossplane-lint
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  mode: keep-existing
  # Goreleaser cannot link to artifactory and we don't want attachments in Gitlab.
  skip_upload: true

changelog:
  use: git
  groups:
    - title: New Features
      regexp: '^[\w\d]+\sfeat(\([\w-_\d]+\))?!?:.*$'
      order: 0
    - title: Bug fixes
      regexp: '^[\w\d]+\sfix(\([\w-_\d]+\))?!?:.*$'
      order: 1
    - title: Others
      regexp: '^[\w\d]+\s(build|chore|ci|docs|style|refactor|perf|test)(\([\w-_\d]+\))?!?:.*$'
      order: 999
